# Redis konfiguratsiya
bind 0.0.0.0
protected-mode no

maxmemory 512mb
maxmemory-policy allkeys-lru

# Persistence
save 3600 1
save 300 100
save 60 10000

appendonly yes
appendfsync everysec

# Logging
loglevel notice
